export const ErrCodes = {
  HOST_TIMEOUT: 'HOST_TIMEOUT',
  HOST_COMM_ERROR: 'HOST_COMM_ERROR',
  HOST_MESSAGE_ERROR: 'HOST_MESSAGE_ERROR',
  HOST_OFFLINE: 'HOST_OFFLINE',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
}
export const Something = {

}
